bank:
  pos_id: 145227
  pos_auth_key: XXX
  key1: XXX
  key2: 13a980d4f851f3d9a1cfc792fb1f5e50
  type: default
  add_signature: true

sms:
  pos_id: 56789
  pos_auth_key: XXX
  key1: XXX
  key2: XXX
  type: sms_premium
  add_signature: false